/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

import java.util.ArrayList;

/**
 *
 * @author Hairul Anam              162410101128
 * @author Muhammad Yusuf Auliya    162410101138
 */
public class Kalkulator extends javax.swing.JFrame {

    private double tempAngka = 0;
    private String operator = "";
    private String username = "";
    private String lastActivity = "";
    private boolean resetAngka = false;
    private ArrayList log;
    private boolean pertamaKali = true;
    private boolean belumDihitung = false;
    
    /**
     * Creates new form Kalkulator
     * @param username
     */
    public Kalkulator(String username) {
        this.username = username;
        initComponents();
        setLocationRelativeTo(null);
        this.usernameTxt.setText(this.username);
        log = new ArrayList();
    }
    
    private boolean isAngkaBulat(double angka){
        return angka % 1 == 0;
    }
    
    private void mensetAngka(String angka){
        if(resetAngka){
            hasilTxt.setText(angka);
        }else{
            if(hasilTxt.getText().equals("0"))
                hasilTxt.setText(angka);
            else
                hasilTxt.setText(hasilTxt.getText()+angka);
        }
        lastActivity = "angka";
        resetAngka = false;
        pertamaKali = false;
    }
    
    private void hitungOperator(String op){
        if(!pertamaKali){
            resetAngka = true;
            operator = op;
            if(lastActivity.equals("operator")){
                hitung();
                log.remove(log.size()-1);
            }else{
                if(isLogTerakhirOperator()){
                    hitung();
                }else{
                    if(tempAngka == 0){
                        tempAngka = Double.parseDouble(hasilTxt.getText());
                    }else{
                        if(op.equals("+"))
                            tempAngka += Double.parseDouble(hasilTxt.getText());
                        else if(op.equals("-"))
                            tempAngka -= Double.parseDouble(hasilTxt.getText());
                        else if(op.equals("x"))
                            tempAngka *= Double.parseDouble(hasilTxt.getText());
                        else if(op.equals("/"))
                            tempAngka /= Double.parseDouble(hasilTxt.getText());
                    }
                }
                operator = op;
                lastActivity = "operator";
                log.add(hasilTxt.getText());
            }
            log.add(operator);
            logTxt.setText(log.toString().replace("[", "").replace("]", "")
                    .replace(",", "")
                    .replace(" ", ""));
            if(tempAngka != 0){
                String angka = isAngkaBulat(tempAngka) ? (int) tempAngka+"" : tempAngka+"";
                hasilTxt.setText(angka+"");
            }
        }
    }
    
    private boolean isLogTerakhirOperator()
    {
        if(log.size() > 0){
            String logTerakhir = log.get(log.size()-1).toString();
            boolean con = logTerakhir.equals("+") || logTerakhir.equals("/") || logTerakhir.equals("x") || logTerakhir.equals("-");
            if(con){
                operator = logTerakhir;
            }
            return con;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logTxt = new javax.swing.JTextField();
        hasilTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSamaDg = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        usernameTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Zaman Now");
        setMinimumSize(new java.awt.Dimension(200, 280));
        setPreferredSize(new java.awt.Dimension(220, 300));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        logTxt.setEnabled(false);
        logTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logTxtActionPerformed(evt);
            }
        });
        getContentPane().add(logTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        hasilTxt.setEditable(false);
        hasilTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hasilTxt.setEnabled(false);
        hasilTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilTxtActionPerformed(evt);
            }
        });
        getContentPane().add(hasilTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 30));

        jButton1.setText("1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jButton2.setText("2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jButton3.setText("3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jButton4.setText("4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jButton5.setText("5");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jButton6.setText("8");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jButton7.setText("7");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jButton8.setText("6");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jButton9.setText("9");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, -1));

        btnClear.setText("c");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 40, -1));

        btnSamaDg.setText("=");
        btnSamaDg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSamaDgMouseClicked(evt);
            }
        });
        btnSamaDg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSamaDgActionPerformed(evt);
            }
        });
        getContentPane().add(btnSamaDg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 40, -1));

        jButton12.setText("0");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        btnPlus.setText("+");
        btnPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusMouseClicked(evt);
            }
        });
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        btnKali.setText("x");
        btnKali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKaliMouseClicked(evt);
            }
        });
        getContentPane().add(btnKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 40, -1));

        btnBagi.setText("/");
        btnBagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBagiMouseClicked(evt);
            }
        });
        getContentPane().add(btnBagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 40, -1));

        btnMinus.setText("-");
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusMouseClicked(evt);
            }
        });
        getContentPane().add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 40, -1));

        usernameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameTxt.setText("PapaAnam");
        usernameTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hasilTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilTxtActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        mensetAngka("1");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        mensetAngka("2");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        mensetAngka("3");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        mensetAngka("4");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        mensetAngka("5");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        mensetAngka("6");
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        mensetAngka("7");
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        mensetAngka("8");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        mensetAngka("9");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        if(resetAngka){
            hasilTxt.setText("0");
        }else{
            if(!hasilTxt.getText().equals("0"))
                hasilTxt.setText(hasilTxt.getText()+"0");
            else
                hasilTxt.setText("0");
        }
        lastActivity = "angka";
        resetAngka = false;
        pertamaKali = false;
    }//GEN-LAST:event_jButton12MouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        hasilTxt.setText("");
        logTxt.setText("");
        log.clear();
        tempAngka = 0;
        pertamaKali = true;
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMouseClicked
        hitungOperator("+");
    }//GEN-LAST:event_btnPlusMouseClicked

    
    private void logTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logTxtActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnSamaDgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamaDgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSamaDgActionPerformed

    private void btnSamaDgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSamaDgMouseClicked
        if(!pertamaKali){
            log.clear();
            logTxt.setText("");
            lastActivity = "operator";
            resetAngka = true;
            hitung();
            String angka = isAngkaBulat(tempAngka) ? (int) tempAngka+"" : tempAngka+"";
            hasilTxt.setText(angka+"");
            tempAngka = 0;
            pertamaKali = true;
        }
    }//GEN-LAST:event_btnSamaDgMouseClicked

    private void hitung()
    {
        switch(operator){
            case "+" :
                tempAngka += Double.parseDouble(hasilTxt.getText());
                break;
            case "-" :
                tempAngka -= Double.parseDouble(hasilTxt.getText());
                break;
            case "/" :
                tempAngka /= Double.parseDouble(hasilTxt.getText());
                break;
            case "x" :
                tempAngka *= Double.parseDouble(hasilTxt.getText());
                break;
        }
    }
    
    private void btnMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseClicked
        hitungOperator("-");
    }//GEN-LAST:event_btnMinusMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnKaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaliMouseClicked
        hitungOperator("x");
    }//GEN-LAST:event_btnKaliMouseClicked
    
    private void btnBagiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBagiMouseClicked
        hitungOperator("/");
    }//GEN-LAST:event_btnBagiMouseClicked

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
//        System.out.println(evt.getKeyChar());
//        System.out.println(evt.getKeyCode());
//        System.out.println(evt.getKeyLocation());
    }//GEN-LAST:event_formKeyTyped

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        System.out.println("Mouse entered");
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        System.out.println("Mouse exited");
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        System.out.println("Mouse pressed");
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        System.out.println("Mouse released");
    }//GEN-LAST:event_jButton1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator("PapaAnam").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSamaDg;
    private javax.swing.JTextField hasilTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField logTxt;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
